environment: pre-prod

image:
  repository: ghcr.io/prod-b2b-ggj-platform/kernel-component
  tag: 10.0.0.1-pre-prod
  pullPolicy: IfNotPresent

replicaCount: 5

resources:
  requests:
    cpu: "4000m"
    memory: "4Gi"
  limits:
    cpu: "8000m"
    memory: "8Gi"

env:
  SPRING_PROFILES_ACTIVE: prod
  DATABASE_URL: jdbc:postgresql://postgres-preprod:5432/kernel_preprod
  REDIS_HOST: redis-preprod
  KAFKA_BOOTSTRAP_SERVERS: kafka-preprod:9092

ingress:
  enabled: true
  host: kernel-preprod.gograbjob.com
  tls:
    enabled: true

