apiVersion: v1
kind: Service
metadata:
  name: kernel-component
  labels:
    app: kernel-component
    component: kernel
    cluster: kernel-cluster
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    app: kernel-component
  sessionAffinity: None
